Added more dotfiles and scripts scpecific to Ubuntu

diff --git a/.scripts/github-changes-not-commited b/.scripts/github-changes-not-commited
--- a/.scripts/github-changes-not-commited
+++ b/.scripts/github-changes-not-commited
@@ -13,23 +13,31 @@ ERROR_LOG=/tmp/$(basename $0).$$
 echo "Searching changes not yet commited on \"$GITHUB_PROJECTS_HOME\":"
 cd "$GITHUB_PROJECTS_HOME"
 
-for d in `find . -maxdepth 1 -type d ! -name '.'`
+for u in `find . -maxdepth 1 -type d ! -name '.'`
 do
-    d=`basename $d`
-    pushd "$d" &> /dev/null
-    [ -d '.git' ] || {
-        echo "At \"$d\": not a git repository!"
+    u=`basename $u`
+    pushd $u &> /dev/null
+
+    for d in `find . -maxdepth 1 -type d ! -name '.'`
+    do
+        d=`basename $d`
+        pushd "$d" &> /dev/null
+        [ -d '.git' ] || {
+            echo "At \"$u/$d\": not a git repository!"
+            popd &> /dev/null
+            continue
+        }
+        changes=$(git status -s) 2> $ERROR_LOG || {
+            echo "'git status -s' output an error for \"$u/$d\":"
+            cat $ERROR_LOG
+        }
+        [ "$changes" ] && {
+            echo -e "At \"$u/$d\":"
+            echo -e "$changes\n"
+        }
         popd &> /dev/null
-        continue
-    }
-    changes=$(git status -s) 2> $ERROR_LOG || {
-        echo "'git status -s' output an error for \"$d\":"
-        cat $ERROR_LOG
-    }
-    [ "$changes" ] && {
-        echo -e "At \"$d\":"
-        echo -e "$changes\n"
-    }
+    done
+
     popd &> /dev/null
 done
 
